In [9]:
import math
import numpy as np

In [10]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.9/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in 

In [11]:
math.sqrt(56)

7.483314773547883

In [12]:
x = [1, 2, 3]


In [14]:
math.sqrt([1, 2, 3])

TypeError: must be real number, not list

In [15]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [16]:
type(np.sqrt(x))

numpy.ndarray

In [17]:
a = np.array([1, "two", 3])

In [18]:
a

array(['1', 'two', '3'], dtype='<U21')

In [19]:
a[1] = "a long long long long long long long asdsadasdasdasdasdsadasd"

In [20]:
a

array(['1', 'a long long long long', '3'], dtype='<U21')

In [21]:
a = np.array([1, "two", 3], dtype="object")

In [22]:
a

array([1, 'two', 3], dtype=object)

In [23]:
a[1] = "a long long long long long long long asdsadasdasdasdasdsadasd"

In [24]:
a

array([1, 'a long long long long long long long asdsadasdasdasdasdsadasd',
       3], dtype=object)

In [25]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
arr = np.array(list_of_lists)

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
arr.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [33]:
np.matmul(arr.reshape(1, 9), arr.reshape(9, 1))

array([[285]])

In [34]:
arr[1, 2]

6

In [35]:
arr[1, :]

array([4, 5, 6])

In [36]:
arr[:, 2]

array([3, 6, 9])

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [38]:
arr1 + arr2

array([5, 7, 9])

In [39]:
arr3 = np.array([1, 2, 3, 4])
arr3 + arr1

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [47]:
1 < 2
2 >= 4
1 != 2

3 != 3

1 == 2
1 == 1
1 == 1.

True

In [48]:
[1, 2, 3] > [4, 7, 9]

False

In [50]:
[6, 8, 3] > [4, 8, 7] #Try this at home! Try lists of strs and lists of various length. What if the first elements coincide?

True

In [51]:
#import numpy as np
earnings = np.array([100, 200, 300, 200, 123, 3423])

In [54]:
earnings[earnings > 200]

array([ 300, 3423])

In [56]:
np.where(earnings > 200, earnings * 0.87, 0)

array([   0.  ,    0.  ,  261.  ,    0.  ,    0.  , 2978.01])

In [60]:
1 or 0

1

In [61]:
[1, 2] and [1, 3]

[1, 3]

In [63]:
[] or [1, 3]

[1, 3]

In [64]:
earnings

array([ 100,  200,  300,  200,  123, 3423])

In [71]:
#day = input()
day = 1

if earnings[int(day)] > 200:
    print("a good day")
    print("asdsa")
    print("asdsad")
    
    if earnings[int(day)] > 1000:
        print("a perfect day!")
else:
    print("else block")
    pass 

print("wow!")

else block
wow!


In [73]:
#day = input()
day = 5

if earnings[int(day)] < 200:
    print("a good day")
    print("asdsa")
    print("asdsad")    
elif earnings[int(day)] > 1000:
    print("elif block!")
else:
    print("else block")
    pass 

print("wow!")

elif block!
wow!


In [76]:
stocks = ["AMZN", "TSLA", "MSFT"]

for stock in stocks:
    print(stock)

AMZN
TSLA
MSFT


In [77]:
for index, stock in enumerate(stocks):
    print(stock, index)

AMZN 0
TSLA 1
MSFT 2


In [79]:
x = [1, 2, 3]

t = x.__iter__()

In [83]:
t.__next__()

StopIteration: 

In [86]:
for index, stock in enumerate(stocks):
    if stock == "TSLA":
        break
    print(stock, index)

AMZN 0


In [87]:
stocks

['AMZN', 'TSLA', 'MSFT']

In [88]:
stock_prices = [100, 200, 300]
stocks_dict = dict(zip(stocks, stock_prices))
stocks_dict

{'AMZN': 100, 'TSLA': 200, 'MSFT': 300}

In [89]:
stocks_dict["TSLA"]

200

In [90]:
stocks_dict["GAZP"]

KeyError: 'GAZP'

In [92]:
stocks_dict.get("GAZP")
stocks_dict.get("TSLA")

200

In [93]:
stocks_dict.keys()

dict_keys(['AMZN', 'TSLA', 'MSFT'])

In [94]:
stocks_dict.values()

dict_values([100, 200, 300])

In [95]:
stocks_dict.items()

dict_items([('AMZN', 100), ('TSLA', 200), ('MSFT', 300)])